### ISSUE TITLE
As a user I want to upload and deploy a blueprint trough the UI

### ISSUE THREAD

**Issue by danielsneijers** [magneticio/vamp#173]
The basic flow of deploying a blueprint should be possible trough the use interface. This means the following interactions should be in place:

### Creating/Uploading the blueprint
Upload blueprint/breed trough copy/pasting in a textarea, and an 'upload file' button in the UI. Bonus: enabling drag and drop for yaml/json files. 

### Interactions with the artefacts should work and feel polished and responsive
This means the detail views should show a decent representations of the content and the edit/deploy/delete buttons in the list views should all execute the corresponding action. This also means that feedback should always be present when an action is taken in the form of a loading state, including elements that aren't visible but loading. Screen transitions are also part of this.

### Optional but recommended
CSS should be refactored a bit

**Comment by tnolet** [comment]
This story is almost finished. It's missing one thing as far as I can see:

When a blueprint is syntactically correct, but semantically incorrect (maybe a port referencing a cluster that does not exist due to a typo), you can still deploy it without getting an error. The backend does respond synchronously with an error specifying what is wrong. 

This means we should have a validation step once a user presses the "deploy" button. We only proceed to the deployment screen when the backend returns a `202 Accepted`

**Comment by danielsneijers** [comment]
fixed, see issue #246
