### ISSUE TITLE
Unpredictable result sava sample app

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#227]
Hi,

I followed the tutorial and deployed the sava project using the blueprint that distributes load evenly.  This works, but in refreshing the browser I get all kind of different results:

1. html from version 1, css from version 1 and javascript from version 2 -> No 'lorem ipsum' text
2. html from version 1, css from version 2 and javascript from version 1 -> dark background, but version 1 logic
3. html from version 2, css & javascript from version 1

I guess that this is because the browser makes multiple requests and for each request it decides which version it should route. This leads to unpredictable results.

You can also see this in the documentation:
![screenshot 2015-06-26 08 47 36](https://cloud.githubusercontent.com/assets/210142/8372099/0e465f46-1be0-11e5-97b2-23514894e643.png)

The 1.0 version should have a light background and 1 column. Version 2 should have the dark background and 2 columns.

**Comment by tnolet** [comment]
@jgordijn. The image is old! sorry for the confusion, we will update it. Furthermore, this is actually expected behaviour, but our description in the tutorial might be a bit short and the images confusing. Before you filter on user agent, each specific request will be send to either route.
Only when you add the specific user-agent filter is every request bound to a specific version of the app.
Once we introduce proper state handling based on cookies, we can mitigate this. For now, expect completely statelessness between each resource request.

**Comment by jgordijn** [comment]
Agreed. So probably this should be stated more explicitly in the documentation, right? Do you prefer a new issue, or solve it under this issue?
