### ISSUE TITLE
Why are dependencies on breed level and not on cluster level?

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#250]
It seems that dependencies need to be referring to breeds. Isn't it more logical in (most) use-cases to refer dependencies to clusters, and thus make all breeds inside a cluster automatically dependencies?

NB this question was inspired by Bernd Zuther's e-commerce setup and blueprints where he seems to get errors and unexpected behaviour because he's referring to clusters as dependencies:

product:
  services:
    -
      breed:
        name: product:a
        deployable: zutherb/product-service
        ports:
          port: 18080/http
        environment_variables:
          MONGODB_PORT_27017_TCP_ADDR: $mongodb.host
          MONGODB_PORT_27017_TCP_PORT: $mongodb.ports.port
        dependencies:
          mongodb: mongodb
      scale:
        instances: 1
        cpu: 0.1
        memory: 128
      routing:
        weight: 95
    -
      breed:
        name: product:b
        deployable: zutherb/product-service:latest-go
        ports:
          port: 18080/http
        environment_variables:
          MONGODB_PORT_27017_TCP_ADDR: $mongodb.host
          MONGODB_PORT_27017_TCP_PORT: $mongodb.ports.port
        dependencies:
          mongodb: mongodb
      scale:
        instances: 1
        cpu: 0.1
        memory: 128
      routing:
        weight: 5

And i would like to used it in the catalog breed in the way:
catalog:
  services:
    breed:
      name: catalog
      environment_variables:
        PRODUCT_PORT_18080_TCP_ADDR: $product.host
        PRODUCT_PORT_18080_TCP_PORT: $product.ports.port
      dependencies:
        product: product

**Comment by tnolet** [comment]
Dependencies are now based on breeds, because breeds have specific versioning, referable in a static artefact. 

This means version x can depend on version y, regardless of runtime state. This is the most strict way of handling version dependency and is 100% analogous to package managers Maven, NPM, Gem or similar. 

There is however no reason we could not extend this dependency mechanism to include a somewhat less strict version where a cluster functions as a dependency. The exact checking of whether all services in a cluster are actually compatible with the services that depend on them is left to the user.
