### ISSUE TITLE
Additional endpoint not always needed and creates problems with headers (and thus cookies)

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#29]
- if cluster route is not yet created, route port will get value from the endpoint
- if cluster route already exists (e.g. canary release), additional endpoint route will be created (same as it is now)

**Comment by tnolet** [comment]
These endpoint routes have a problem the way they are created now. Because they sit in front of the other routers and do calls to essentially to localhost using TCP/HTTP the initial headers that arrive at the endpoint are not passed down to the other, underlying routes. This means some filters will not work anymore. 

The solution is to use an endpoint route that uses the PROXY protocol via unix sockets. We already use this in the routes. In this way all original headers and metadata is preserved and the endpoint route really functions as a proxy. We could pretty simply introduce a new route type in Vamp Router that does only this and has no other fancy functions.

**Comment by tnolet** [comment]
This is superseded by https://github.com/magneticio/vamp/issues/167
