### ISSUE TITLE
conf-files not copied

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#298]
Wanted to do a clean install of Vamp this morning so I ran the appropriate uninstall commands. I than noticed that the uninstall doesn't remove /usr/share/vamp-*-folders. Don't know if this is by design (to preserve existing conf-files). So I removed them by hand:

```$ rm -rf /usr/share/vamp-*```

And afterwards I run ubuntu 14.04-instructions (apt-get install). Vamp wouldn't start. With some digging I found that the configuration-folders of vamp-core, vamp-router and vam-pulse weren't copied. Copied them by hand from the Debian-packages and everything worked. A very small point regarding the configuration-folders: vamp-router has a configuration-folder, the other ones have a conf-folder.

**Comment by plamola** [comment]
Not removing the configuration files it not by design; I guess it is something I've to add to the postrm script, to remove it explicitly. Thanks for reporting this.

Not sure why the configuration files are missing, when reinstalling the package. I've seen this issue once, during a development test of the packages, but assumed it was due to some incorrect package settings at that time. This will need some further investigation.

As for the different naming of the vamp-router configuration directory; this is a correct observation. The directory structure used by vamp-router is a little different from the other Vamp modules. Something we might change in the future.

**Comment by plamola** [comment]
I've looked up the Debian policy for handling config files and actually, config files must be preserved when removing a package:
https://www.debian.org/doc/debian-policy/ch-files.html#s10.7.3

> Configuration file handling must conform to the following behavior:
> * local changes must be preserved during a package upgrade, and
>* configuration files must be preserved when the package is removed, and only deleted when the package is purged.


So, purge the files when uninstalling the package

```bash
sudo apt-get remove --purge packagename
```

or purge them at a later stage: 

```bash
sudo apt-get purge packagename
```

**Comment by JoshFalken** [comment]
thanks!
