### ISSUE TITLE
Suggestion: delete deployment without all the information

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#356]
When I use the API and want to delete a deployment I have to include all the data (as stated in the documentation). VAMP doesn't do anything with only a name. In practice this comes down to obtaining the information on the deployment, transforming this to yaml and subsequently calling delete. It would be a lot easier to just allow a delete with only the name.

**Comment by dragoslav** [comment]
There were 2 reasons:
- to be consistent with add/remove a blueprint to deployment (e.g. deploy A, add B, remove A, and if you want to remove all, remove B).
- additional validation - deployment is supposed to run for longer time even though it's dynamic in sense of services are being added/removed. So complete removal shouldn't be that common and specifying all services shouldn't be an issue - get deployment as blueprint ("as_blueprint=true", doesn't matter if JSON or YAML) and then delete.

Since we can with one click undeploy (UI) and the first argument is not that strong, we could easily remove this constraint soon (it's a trivial change in the code anyway).

**Comment by JoshFalken** [comment]
@dragoslav: thanks for the clarification! I understand the rationale but to me it seems more logical to use 'update' instead of delete/add on existing deployments to delete or add parts. Especially when you compare the function of delete/add to the other branches of the api. But that's probably a matter of taste.

**Comment by dragoslav** [comment]
In case of deployment we don't follow even the usual REST semantic - one resource (deployment) is created/modified/deleted using another resource (blueprint). The most similar way to common REST is to get the deployment as a blueprint and send it back (modified) to server in order to change its state.
This (uncommon) 2 resource approach allows separation of having a blueprint of services and running them in different setup - A/B/C testing, canary releases etc. So Vamp takes care of wiring things up and the blueprints alone represent more an ideal single state (i.e. the one version only - A or B).

**Comment by JoshFalken** [comment]
@dragoslav : that first scenario was exactly the scenario I was thinking of. I was indeed surprised the first time I added a deployment and VAMP added a blueprint and a breed by itself. I wouldn't expect that. Thanks again for the clarification.
