### ISSUE TITLE
VAMP does not restart crashing docker image

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp#375]
Test steps:
1. Deploy SAVA with blueprint as on (http://vamp.io/documentation/guides/getting-started-tutorial/1-deploying/)
2. run `docker stop ####` with ### the id of the container

VAMP sees that the service is gone and places show in the UI: `readyfordeployment`. However, SAVA does not get redeployed.

VAMP LOG:
```
 [DEPLOY] Container /vamp_2f1fe8d1-d67f-46ba-b9a0-923388ef5f7d_6fd83b1fd01f7dd9eb7f already exists, no action
```

**Comment by plamola** [comment]
Problem with the docker driver implementation is it has to create the image, before it can start it. 

While it is creating the image, which might take some time, due to the docker pull of the image, it is constantly being told by Vamp Core to start it. To prevent the image from being started multiple times, in different threads, only the thread creating the image will be allowed to start it.

This works fine for starting a docker images, but this prevents recovery.

To fix is, the docker driver will need to keep state; ignoring start requests when it is already busy starting the container.

**Comment by tnolet** [comment]
This is an accepted limitation of the Docker driver. Docker driver is only for local testing and doesn't have any of the redundancy and failover guarantees of Marathon. It's like manually killing your local Tomcat. On your laptop it will not be restarted automatically.

**Comment by dragoslav** [comment]
it was the problem with local docker driver cache - it's fixed.
