### ISSUE TITLE
Blueprint editor

### ISSUE THREAD

**Issue by faddat** [magneticio/vamp#386]
How do people feel about:

 - Giving the blueprint editor a fixed-width font?
 - Adding real-time collaboration to the blueprint editor by making it from an embedded etherpad-lite?

If people like the sound of this, I can make it something I'm working towards.

**Comment by plamola** [comment]
Fixed-width font makes sense for yaml/json editting.

Not sure about the real-time collaboration on a blueprint.
Are you using by any change inline breeds in the blueprints?

I would advise to create breeds and only reference the breeds in the blueprints, instead of inline breeds in the blueprint. This would limit the necessary edits on the blueprint.

Would that work for your workflow?

**Comment by danielsneijers** [comment]
Definitely on board with the fixed-width font, that'll feel more familiar to most developers. About the real time editing: I don't know if that will be useful for users or not, but I wonder how that would work technically. Do you need external resources for that? The UI is build to be self contained so it can be easily used in every environment, so adding external resources to the UI would not be my first choice.
