### ISSUE TITLE
Log usage statistics

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#473]
Log usage statistics for analysing scale of usage and usage reporting.

**Comment by dragoslav** [comment]
`/statistics` endpoint, example:

- number of (re)deployed services (ever)
- number of artifacts per type
- number of API calls per type (could be only non-read calls based on archiving)
- current number of deployments, services and gateways
- number of ran workflows (this could be added also later, when we improve Workflow engine) 

`/info` endpoint, additional:
- running since
- installation time (ES index initialization time)
- unique Vamp run-time ID

**Comment by olafmol** [comment]
Sounds good. Additional:
- number of errors (for deploy validation)
- number of scaling actions (SLA events)
- number of visitors (unique requests coming in on endpoints)

**Comment by dragoslav** [comment]
number of validation error is not added, also some stats will be done in #530 and #531
