### ISSUE TITLE
Add documentation for virtual host

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp#613]
https://github.com/magneticio/vamp/issues/589
https://github.com/magneticio/vamp/issues/611

**Comment by agemooij** [comment]
I would say the issue is bigger: i.e. add entity schema references and examples to all API reference docs. As long as you don't provide any examples, the user will have to guess at the entities expected here.

Also, as soon as yo start documenting your entities, versioning will be a problem you will have to deal with and it's better to think about it now than later. 

A lot of people tend to go for the `/v2/api/etc` approach but IMHO that is and extremely coarse-grained approach. Nothing wrong with it if you only plan to update your API once every few years.

We use the versioned media-type approach, like this:

    application/vnd.blaze.product.searchresults+json; version=1.2.3

Some additional benefits:

- finer grained
- self-documenting references to the relevant entity schemas
- enables a backwards compatibility mode

**Comment by olafmol** [comment]
tnx Age!

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp/issues/665
https://github.com/magneticio/vamp/issues/666
