### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by Kravs** [magneticio/vamp#618]
Hello all 
I have running three Ubuntu machines (Web X2, DBx1) and I have some small questions:

Could I move my web tier(2 machines) to VAMP to achieve canary builds?
I walked throw docs (quickly) and didn't find anything about how to add instances to VAMP deployment.

Where to install VAMP itself? Near web app, separate host or just laptop ?

**Comment by olafmol** [comment]
Hello @Kravs, there are no dumb questions :) If you have your application running inside docker-containers it's easy to have these managed by VAMP to enable canary-patterns. If you have a "legacy" application you can use VAMP gateways (http://vamp.io/documentation/using-vamp/gateways/) to "canary-move" traffic from one endpoint/app to another endpoint/app

You can install VAMP on the same server(s) where you have your container-cluster manager running, f.e. on the mesos-master. VampGatewayAgents can be installed on each host/node or on specific machines. More info: http://vamp.io/installation/

**Comment by Kravs** [comment]
I'm having my app running  without containers, I'm investigation what I need to go with VAMP?
I need to instll docker on each machine, put app inside docker and run VAMP somewhere, right?
Or I'm missing something.... 
In tutorials from vamp.io I cna see that only docker is needed...but there is only one instance.
Do I need something between VAMP and docker, if I have 3 instances? Something that will tight 3 instances together? Mesos? Another option? 
Sorry it's just not clear for me, what is beetween doker running conteiners on 3 machines and VAMP?

**Comment by dragoslav** [comment]
Minimal setup:
-  HAProxy with Vamp Gateway Agent (VGA) - either standalone or using Docker. Better to have more than 1 instance of them, otherwise it would be a single point of failure
- Zookeeper or Etcd or Consul - Vamp stores HAProxy configuration in one of these key-value stores (among the other things they provide)
- Vamp - if you are not using Mesos/Kubernetes etc. then you can run Vamp just to store the configuration to ZK, etcd or Consul - so even from your laptop (by default Vamp needs Elasticsearch as a persistence storage). 

Additionally you would like probably to get some metrics and VGA can send all request/response metrics to Logstash, so you should setup Elasticsearch + Logstash somewhere.

In this setup basically you have a redundant router (HAProxy and VGA to manage it) with programmable routing, e.g. filters, weights, filter strength...  and only when you want to change something (gateways) you can run Vamp and use its API.

**Comment by olafmol** [comment]
@Kravs if you have multiple machines for your web tier you need a container-cluster manager. This can be DC/OS (www.dcos.io) or mesos/marathon. We are working on Kubernetes and Rancher integration, and the Docker driver uses the Docker API, which should be compatible with Docker Swarm (we didn't formally test this, but it's reported that it works). I would suggest starting out with DC/OS, and use VAMP as a DC/OS package.

**Comment by Kravs** [comment]
Thanks, I think that is missing puzzle in my investigation.
Is there any guide how to connect VAMP to dc/os ?

**Comment by dragoslav** [comment]
http://vamp.io/documentation/installation/mesosphere_dcos/

**Comment by Kravs** [comment]
Oh...Mesosphere DC/OS ...
I thought that is different products...
But thanks for answers.
I will take a look into that

**Comment by olafmol** [comment]
DC/OS is the opensource version, which is based on mesosphere DCOS, which is based on mesos/marathon. DC/OS adds an additional management layer on top of mesos
