### ISSUE TITLE
Make Quickstart work with (native) Docker for Mac and Windows

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#623]
https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

Our quickstart commands need to be extended to work with the new native Docker clients.

**Comment by dragoslav** [comment]
Works with beta, let's wait also for the official release.

**Comment by olafmol** [comment]
Does it need a specific commandline (ie different from our Toolbox commandline) to make it work?

**Comment by Ruben-E** [comment]
I would like to know this as well.

**Comment by dragoslav** [comment]
Ideally `--net=host` **should work** but for now it doesn't, e.g. https://forums.docker.com/t/should-docker-run-net-host-work/14215 and many other (it seems it works on Windows based on some reports but didn't test it).

**Workaround**
```
docker run -v /var/run/docker.sock:/var/run/docker.sock \
           -v /usr/bin/docker:/bin/docker \
           -v "/sys/fs/cgroup:/sys/fs/cgroup" \
           -e "DOCKER_HOST_IP=192.168.65.2" \
           -p 8080:8080 -p 5050:5050 -p 9090:9090 -p 9050:9050 \
           magneticio/vamp-docker:0.8.5-docker-for-mac
```
**Explanation**

Needed to make a small change in the image itself https://github.com/magneticio/vamp-docker/commit/8b80af175dc35af481fcf47d7a38212b3d065185 thus this new tag `0.8.5-docker-for-mac` otherwise it is the same as `0.8.5-marathon`.
Another change is `DOCKER_HOST_IP=192.168.65.2` and IP is `docker-ipv4` parameter (assuming default network configuration):
```
$ pinata list | grep docker-ipv4
*  network = hostnet (docker-ipv4=192.168.65.2, host-ipv4=192.168.65.1)
            Parameters: docker-ipv4 (docker node), host-ipv4 (host node)
```
And finally ports should be explicitly set, in this case Vamp, Mesos, Marathon and custom 9050 `sava` example ports:
```
-p 8080:8080 -p 5050:5050 -p 9090:9090 -p 9050:9050
```
Additional ports should be specified if needed, e.g. 1988 for HAProxy or ports for other custom gateways.

Using all of this provides the following:
- starting Docker containers from `vamp-docker` container
- "linking" HAProxy from `vamp-docker` container to services in another containers
- exposing ports to the host, so `http://localhost:8080` (Vamp) or `http://localhost:9050` (`sava` example) should work.

Anyway, I don't find this as a good solution but`Docker for Mac` is in beta so things still may change on their side.

**Comment by harmw** [comment]
I'm currently testing some stuff on Docker-for-Mac using the following:
```
_HOST=127.0.0.1
docker run \
    --net=bridge \
    --rm \
    --name=vamp-docker \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/bin/docker:/bin/docker \
    -v "/sys/fs/cgroup:/sys/fs/cgroup" \
    -e "DOCKER_HOST_IP=${_HOST}" \
    -p 5601:5601 \
    -p 9200:9200 \
    -p 10001:10001/udp \
    -p 2181:2181 \
    -p 8080:8080 \
    -p 5050:5050 \
    -p 9090:9090 \
    magneticio/vamp-docker:0.9.0
```
This will launch Vamp and all supporting services. You can deploy sava and reach the webpage et. al. The only _issue_ is connecting with VGA since the port 80 mount and hostmode network is failing bad as is already noted in this thread.

Alternatively I tried to run a proxy-based solution, but that doesn't work since the gateway is already bound to port 80 on the xhyve-based docker instance.

**Comment by olafmol** [comment]
closing this for now as the "docker for mac and win" versions seem to have limited networking options to support our usecases.
