### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by JoshFalken** [magneticio/vamp#639]
Found some small typos/omissions in the documentation:

Global:
- In the docs the notation is :name but it should be {name} or just name. I thought the colon was mandatory.
- Delete: The docs don't reflect that you have to include the item you want to delete as a payload.

On [http://vamp.io/documentation/api-reference/metrics-events/](http://vamp.io/documentation/api-reference/metrics-events/)
- Lists metrics and/or events without any pagination or filtering, the call is a POST but should be a get.

**Comment by dragoslav** [comment]
Hi @JoshFalken thanks!
- all `:name` are replaced with `{type_name}`
- `DELETE` with body applies only on deployments http://vamp.io/documentation/api-reference/deployments/#delete-a-deployment-using-a-blueprint
- `POST` for getting events is not a typo (added a note http://vamp.io/documentation/api-reference/metrics-events/) but maybe we will change this event API a bit. For instance to have `POST` with `/query` instead of `/get`

**Comment by JoshFalken** [comment]
Great, thanks!
