### ISSUE TITLE
VGA's throw UDP connection errors on AWS/DCOS 1.7 after a period

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp#768]
From the VGA container output log:

07.315 main NOTI ==> Reloading HAProxy - configuration file: /usr/local/vamp/haproxy.cfg, reload script: /usr/local/vamp/reload.sh [0m
[31m12:44:07.427 main ERRO ==> Can't write: write udp 10.0.0.92:38185->10.0.0.93:10001: write: connection refused [0m
[32m12:44:12.429 main NOTI ==> Connected to remote UDP address: 10.0.0.93:10001 [0m

Result is that metrics are not shown in UI graphs when requesting a service. The routing is ok though.

Killing the VGA in marathon, resizing the ES cluster (from 3 to 1 to 4 to 3 f.e.) and then creating the VGA's in marathon seems to resolve it. Simply restarting the VGA's from marathon keeps one of them in "waiting" state.

**Comment by iamtew** [comment]
This is solved by using the templates in #662. The problem is coming from upstream `logstash.lib.sh` when trying to parse  `JAVA_OPTS` from the environment. This was causing logstash to fail because of bad command line options, and clients where throwing connection refused errors. The current work around is to run with default java options, as these are sufficient for our needs. 

Upstream will fix this in logstash 5, the current offending function in logstash.lib.sh in version 2.2:
https://github.com/elastic/logstash/blob/2adde524e6e0a70f8f65bb42ab109e6ba7d2bb4e/bin/logstash.lib.sh#L137-L142
